[preferred]
# GTK como portal por defecto (selectores de archivos, etc.)
default=gtk

# Niri implementa org.gnome.Mutter.ScreenCast, por eso screencast usa gnome
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome

# El resto usa GTK
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.OpenURI=gtk
org.freedesktop.impl.portal.Print=gtk
